CREATE TABLE CONSUMER(
    CONSUMER_ID NUMBER(10),
    FIRST_NAME VARCHAR2(15) NOT NULL,
    LAST_NAME VARCHAR2(15) NOT NULL,
    PHONE_NO VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(60),

    CONSTRAINT CONSUMER_ID_PK PRIMARY KEY(CONSUMER_ID)
);
--ALTER TABLE CONSUMER ADD COUNTRY  VARCHAR2(10);
--DROP CONSTRAINT CLIENT_ID_FK;
--ADD CONSTRAINT CLIENT_ID_FK FOREIGN KEY(CLIENT_ID) REFERENCES GETTING_SERVICE(CLIENT_ID); 

CREATE TABLE SERVICE(
    SERVICE_ID NUMBER(12),
    SERVICE_NAME VARCHAR2(30) NOT NULL,
    
    CONSTRAINT SERVICE_ID_PK PRIMARY KEY(SERVICE_ID)
);

CREATE TABLE ELEC_USAGE(
    GS_ID NUMBER(10),
    CONSUMER_ID NUMBER(10) NOT NULL,
    SERVICE_ID NUMBER(10) NOT NULL,
    PRESENT_RDG NUMBER(15) CONSTRAINT PRESENT_RDG_MIN CHECK(PRESENT_RDG >= 0),
    PREVIOUS_RDG NUMBER(15) CONSTRAINT PREVIOUS_RDG_MIN CHECK(PREVIOUS_RDG >= 0),
    PRESENT_DATE DATE,
    PREVIOUS_DATE DATE,
    USED NUMBER(15),
    BILL_MONTH VARCHAR2(3),
    BILL_YEAR VARCHAR2(4),
	
    CONSTRAINT ELEC_USAGE_PK PRIMARY KEY(CONSUMER_ID,BILL_MONTH,BILL_YEAR),
    CONSTRAINT CONSUMER_ID_FK FOREIGN KEY(CONSUMER_ID) REFERENCES  CONSUMER(CONSUMER_ID),
    CONSTRAINT SERVICE_ID_FK FOREIGN KEY(SERVICE_ID) REFERENCES SERVICE(SERVICE_ID),
    CONSTRAINT PRESENT_RDG_GREATER_PREV_RDG CHECK(PRESENT_RDG > PREVIOUS_RDG)
);

ALTER TABLE ELEC_USAGE ADD GS_ID NUMBER(10);
ALTER TABLE ELEC_USAGE ADD CONSTRAINT ELEC_USGE_PK PRIMARY KEY(GS_ID,BILL_MONTH,BILL_YEAR);FOREIGN KEY(GS_ID) REFERENCES GETTING_SERVICE(GS_ID);
--DROP TABLE ELEC_USAGE;
--ALTER TABLE ELEC_USAGE RENAME CONSTRAINT USAGE_PK TO ELEC_USAGE_PK;
--ALTER TABLE ELEC_USAGE ADD CONSTRAINT S_RDG_GREATER_E_RDG CHECK(PRESENT_RDG > PREVIOUS_RDG) ENABLE;

CREATE TABLE GAS_USAGE(
    GS_ID NUMBER(10),
    CONSUMER_ID NUMBER(10),
    SERVICE_ID NUMBER(10),
    FURNACE_NUM NUMBER(5),
    BILL_MONTH VARCHAR2(3),
    BILL_YEAR VARCHAR2(4),

    CONSTRAINT GAS_USAGE_PK PRIMARY KEY(CONSUMER_ID,BILL_MONTH,BILL_YEAR),
    CONSTRAINT GAS_USE_CONSUMER_ID_FK FOREIGN KEY(CONSUMER_ID) REFERENCES CONSUMER(CONSUMER_ID),
    CONSTRAINT GAS_USE_SERVICE_ID_FK FOREIGN KEY(SERVICE_ID) REFERENCES SERVICE(SERVICE_ID)
);
ALTER TABLE GAS_USAGE DROP CONSTRAINT GAS_USAGE_PK;
ALTER TABLE GAS_USAGE ADD CONSTRAINT GAS_USGE_PK PRIMARY KEY(GS_ID,BILL_MONTH,BILL_YEAR);
ALTER TABLE GAS_USAGE ADD GS_ID NUMBER(10);
ALTER TABLE GAS_USAGE ADD CONSTRAINT GAS_USGE_GS_FK FOREIGN KEY(GS_ID) REFERENCES GETTING_SERVICE(GS_ID);

--DROP TABLE GAS_USAGE;

CREATE TABLE TELE_USAGE(
    GS_ID NUMBER(10),
    CONSUMER_ID NUMBER(10),
    SERVICE_ID NUMBER(10),
    BILL_DATE VARCHAR2(2),
    BILL_MONTH VARCHAR2(3),
    BILL_YEAR VARCHAR2(4),
    USAGE NUMBER(10),

    CONSTRAINT TELE_USE_PK PRIMARY KEY(CONSUMER_ID,BILL_DATE,BILL_MONTH,BILL_YEAR)
);

ALTER TABLE TELE_USAGE ADD CONSTRAINT TELE_USAGE_PK PRIMARY KEY(GS_ID);
ALTER TABLE TELE_USAGE ADD CONSTRAINT TELE_USGE_GS_FK FOREIGN KEY(GS_ID) REFERENCES GETTING_SERVICE(GS_ID);

--DROP TABLE TELE_USAGE PURGE;

CREATE TABLE COMPANY(
    COMPANY_ID NUMBER(10),
    COMPANY_NAME VARCHAR2(100) NOT NULL,
    PHONE_NO VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(100),
    ADMIN_ID NUMBER(10),
	
    CONSTRAINT COMPANY_ID_PK PRIMARY KEY(COMPANY_ID),
    CONSTRAINT COM_ADMIN_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID) 
);

--ALTER TABLE COMPANY RENAME COLUMN ADMIN TO ADMIN_ID;
--ALTER TABLE COMPANY  ADD  ADMIN_ID NUMBER(10);
--ALTER TABLE COMPANY 
--ADD CONSTRAINT COM_ADMIN_FK FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID);
--COMMIT;

CREATE TABLE SERV_PROVIDER(
    COMPANY_ID NUMBER(10),
    SERVICE_ID NUMBER(12),
    SP_DATE DATE,
	
    CONSTRAINT SERV_PROVIDER_PK PRIMARY KEY(COMPANY_ID,SERVICE_ID),
    CONSTRAINT SP_COMPANY_ID_FK FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY(COMPANY_ID),
    CONSTRAINT SP_SERVICE_ID_FK FOREIGN KEY(SERVICE_ID) REFERENCES SERVICE(SERVICE_ID)
);

CREATE TABLE COM_CUS(
    COMPANY_ID NUMBER(10),
    CONSUMER_ID NUMBER(10),
    GET_SERV_DATE DATE,
    END_SERV_DATE DATE,
     
    CONSTRAINT COM_CUS_PK PRIMARY KEY(COMPANY_ID,CONSUMER_ID),
    CONSTRAINT COMPANY_ID_FK FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY(COMPANY_ID) ,
    CONSTRAINT CONSUMER_ID_FK_COM FOREIGN KEY (CONSUMER_ID) REFERENCES CONSUMER(CONSUMER_ID)
);

--DROP TABLE COM_CUS PURGE;
--ALTER TABLE COM_CUS ADD END_SERV_DATE DATE;

CREATE TABLE STATUS(
    STATUS_ID NUMBER(5),
    STATUS_NAME VARCHAR2(15) NOT NULL,
	
    CONSTRAINT STATUS_ID_PK PRIMARY KEY(STATUS_ID) 
);

CREATE TABLE LOGININFO(
    EMAIL_ID VARCHAR2(60),
    PASSWORD VARCHAR2(15) NOT NULL,
    STATUS_ID NUMBER(10),
    CONSUMER_ID NUMBER(10),
    
    CONSTRAINT EMAIL_ID_PK PRIMARY KEY(EMAIL_ID),
    CONSTRAINT STATUS_ID_FK FOREIGN KEY(STATUS_ID) REFERENCES STATUS(STATUS_ID)
);
--ALTER TABLE LOGININFO
--ADD CONSTRAINT STATUS_ID_FK FOREIGN KEY(STATUS_ID) REFERENCES STATUS(STATUS_ID);


CREATE TABLE GETTING_SERVICE(
    GS_ID NUMBER(10),
    CONSUMER_ID NUMBER(10),
    CLIENT_ID NUMBER(10),
    SERVICE_ID NUMBER(12),
    COMPANY_ID NUMBER(10),
    STATUS_ID NUMBER(5),
    EMAIL VARCHAR2(60),
    INITIAL_RDG NUMBER(10)
    INITIAL_DATE DATE,
    
    CONSTRAINT GETTING_SERV_PK PRIMARY KEY(GS_ID),
    CONSTRAINT GET_SERV_CONSUMER_ID_FK FOREIGN KEY(CONSUMER_ID) REFERENCES CONSUMER(CONSUMER_ID),
    CONSTRAINT GET_SERV_SERVICE_ID_FK FOREIGN KEY(SERVICE_ID) REFERENCES SERVICE(SERVICE_ID),
    CONSTRAINT GET_SERV_COMPANY_ID_FK FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY(COMPANY_ID),
    CONSTRAINT GS_STATUS_ID_FK FOREIGN KEY(STATUS_ID) REFERENCES STATUS(STATUS_ID)
);
ALTER TABLE GETTING_SERVICE ADD CONSTRAINT GETTING_SERV_PK PRIMARY KEY(GS_ID);
--CREATE TABLE ELECT_BILL_RULE(
--ALTER TABLE GETTING_SERVICE 
--ADD CONSTRAINT GS_CONSUMER_ID_FK FOREIGN KEY(CONSUMER_ID) REFERENCES CONSUMER(CONSUMER_ID);

CREATE TABLE VERIFICATION(
    CLIENT_ID NUMBER(10),
    COMPANY_ID NUMBER(10),
    PID VARCHAR2(20) ,
	
    CONSTRAINT VER_PK PRIMARY KEY(CLIENT_ID,COMPANY_ID),
    CONSTRAINT VER_COMPANY_ID_FK FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY(COMPANY_ID)

);

CREATE TABLE BILL_RULE(
    BILL_RULE_ID NUMBER(10),
    COMPANY_ID NUMBER(10),
    SERVICE_ID NUMBER(10),
    PER_UNIT_COST NUMBER (10),
    SERVICE_CHARGE NUMBER(10),
    FINE_RATE NUMBER(10),
    START_DATE DATE,
    END_DATE DATE,
    CONSTRAINT BILL_RULE_PK PRIMARY KEY(BILL_RULE_ID),
    CONSTRAINT COMPANY_ID_FK_RULE FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(COMPANY_ID),
    CONSTRAINT SERVICE_ID_FK_RULE  FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE (SERVICE_ID)
);

CREATE TABLE BILL(
   BILL_NO NUMBER(10),
   CONSUMER_ID NUMBER(10),
   COMPANY_ID NUMBER(10),
   SERVICE_ID NUMBER(10),
   BILL_MONTH VARCHAR2(3) NOT NULL,
   BILL_YEAR VARCHAR2(4),
   ISSUE_DATE DATE,
   DUE_DATE DATE,
   USED NUMBER(10),
   COSTS NUMBER(10),
   VAT NUMBER(10),
   TOTAL NUMBER(10),
   FINE NUMBER(5),
   STATUS_ID NUMBER(5),
   PAYMENT_DATE DATE,
   
   CONSTRAINT BILL_NO_PK PRIMARY KEY(BILL_NO),
   CONSTRAINT COMPANY_ID_FK_BILL FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(COMPANY_ID),
   CONSTRAINT SERVICE_ID_FK_BILL  FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE (SERVICE_ID),
   CONSTRAINT CONSUMER_ID_FK_BILL FOREIGN KEY(CONSUMER_ID) REFERENCES CONSUMER(CONSUMER_ID),
   CONSTRAINT STATUS_ID_FK_BILL FOREIGN KEY(STATUS_ID) REFERENCES STATUS(STATUS_ID)
);
ALTER TABLE BILL ADD GS_ID NUMBER(10);
--DROP TABLE BILL PURGE;
ALTER Table BILL
ADD CONSTRAINT BILL_GS_ID_FK FOREIGN KEY(GS_ID) REFERENCES GETTING_SERVICE(GS_ID);

CREATE TABLE INVOICE (
    INVOICE_ID NUMBER(10),
    CONSUMER_ID NUMBER(10),
    INV_DATE DATE DEFAULT SYSDATE,
    TOTAL_COST NUMBER(15),
    
    CONSTRAINT INVOICE_ID_PK PRIMARY KEY(INVOICE_ID),
    CONSTRAINT CONUMER_ID_FK_INV FOREIGN KEY(CONSUMER_ID) REFERENCES CONSUMER(CONSUMER_ID)
);

CREATE TABLE INV_ITEM(
    INVOICE_ID NUMBER(10),
    BILL_NO NUMBER(10),
    CONSTRAINT INV_ITEM_PK PRIMARY KEY(INVOICE_ID,BILL_NO),
    CONSTRAINT INVOICE_ID_FK FOREIGN KEY(INVOICE_ID) REFERENCES INVOICE(INVOICE_ID),
    CONSTRAINT BILL_NO_FK FOREIGN KEY(BILL_NO) REFERENCES BILL(BILL_NO)
);

CREATE TABLE ADMIN(
    ADMIN_ID NUMBER(10),
    ADMIN_NAME VARCHAR2(20),
    ADMIN_EMAIL VARCHAR2(60),
    CITY VARCHAR2(10),
    COUNTRY VARCHAR2(10),
    NATIONALITY VARCHAR2(10),
    DOB DATE,
    
    CONSTRAINT ADMIN_PK PRIMARY KEY(ADMIN_ID)
); 
--ALTER TABLE ADMIN ADD DOB DATE;

CREATE TABLE TRANSACTIONS(
    TXN_ID VARCHAR2(20),
    AMOUNT NUMBER(15) CONSTRAINT AMOUNT_NOT_NEGATIVE CHECK(AMOUNT > 0),
    TXN_DATE DATE DEFAULT SYSDATE,
    
    CONSTRAINT TXN_PK PRIMARY KEY(TXN_ID)
);

CREATE TABLE APPLICATIONS(
    
    APPLICATION_ID VARCHAR2(15),
    --APPLICANT'S INFO
    FIRST_NAME VARCHAR2(10),
    LAST_NAME VARCHAR2(10),
    PERSONAL_EMAIL VARCHAR2(10),
    PERSON_CITY VARCHAR2(10),
    PERSON_COUNTRY VARCHAR2(10),
    PERSON_NATIONALITY VARCHAR2(10),
    PERSON_DOB DATE,
    POSITION VARCHAR2(15),
    
    --ORGANISATION INFO
    
    COM_NAME VARCHAR2(15),
    COM_EMAIL VARCHAR2(15),
    COM_WEB VARCHAR2(15),
    TELE_NO VARCHAR2(15),
    LICENSE_NO VARCHAR2(20),
    COM_TYPE VARCHAR2(10),
    COM_ADDRESS VARCHAR2(20),
    CITY VARCHAR2(15),
    POST_CODE VARCHAR2(100),
    COUNTRY VARCHAR2(20),
    START_DATE DATE,
    
    COM_BANK_NAME VARCHAR2(20),
    COM_BANK_BRANCH VARCHAR2(15),
    AC_NAME VARCHAR2(15),
    AC_NO VARCHAR2(15),
    
    STATUS_ID NUMBER(5),
    
    
    CONSTRAINT APPLICATION_PK PRIMARY KEY(APPLICATION_ID),
    CONSTRAINT APP_STATUS_FK FOREIGN KEY(STATUS_ID ) REFERENCES STATUS(STATUS_ID)
);

DROP TABLE APPLICATIONS;
