SELECT * FROM LOGININFO WHERE EMAIL_ID = AND PASSWORD = AND STATUS = 16;
SELECT U.CONSUMER_ID,S.SERVICE_ID,S.SERVICE_NAME,U.PREVIOUS_DATE,U.PRESENT_DATE,U.PREVIOUS_rdg,U.PRESENT_RDG,U.USED,U.BILL_MONTH,U.BILL_YEAR
FROM ELEC_USAGE U,SERVICE S
WHERE U.CONSUMER_ID=150501 AND U.SERVICE_ID=S.SERVICE_ID
order by present_rdg;

SELECT * FROM VERIFICATION WHERE  COMPANY_ID=1000;

UPDATE GETTING_SERVICE SET CONSUMER_ID = WHERE CLIENT_ID = AND COMPANY_ID =


SELECT G.CLIENT_ID, G.SERVICE_ID, S.SERVICE_NAME,G.COMPANY_ID, C.COMPANY_NAME
FROM GETTING_SERVICE G 
JOIN SERVICE S ON(G.SERVICE_ID=S.SERVICE_ID AND CONSUMER_ID=150501 )
JOIN COMPANY C ON (G.COMPANY_ID = C.COMPANY_ID);
WHERE CONSUMER_ID =150501;


SELECT * 
FROM LOGININFO 
WHERE EMAIL_ID = 'mhr@gmail.com' AND PASSWORD='123';

SELECT S.CONSUMER_ID,S.COMPANY_ID,C.COMPANY_NAME
FROM GETTING_SERVICE S JOIN COMPANY C
ON(S.CONSUMER_ID=150501 AND S.COMPANY_ID=C.COMPANY_ID)
GROUP BY S.CONSUMER_ID,S.COMPANY_ID,C.COMPANY_NAME;

SELECT COMPANY_ID,CLIENT_ID,PID
FROM VERIFICATION
WHERE CLIENT_ID=2029 AND COMPANY_ID=1006 AND PID ='16621030-1039' ;

SELECT COMPANY_ID,CLIENT_ID,PID
FROM GETTING_SERVICE
WHERE CLIENT_ID=2097 AND COMPANY_ID=1004;


SELECT CONSUMER_ID FROM GETTING_SERVICE WHERE CLIENT_ID = AND COMPANY_ID = AND SERVICE_ID = 232450;
SELECT CLIENT_ID FROM GETTING_SERVICE WHERE  COMPANY_ID = AND SERVICE_ID = 232450;

SELECT TO_CAHR_(TO_DATE('10/5/2017','DD/MM/YYYY'),'MM')

DECLARE 
P DATE;
BEGIN

P := TO_DATE
SELECT PRESENT_RDG INTO P  FROM ELEC_USAGE WHERE CONSUMER_ID = 150501 AND SERVICE_ID = 232450 AND BILL_MONTH = 12 AND BILL_YEAR = 2017;
 
 IF P IS NULL THEN
   DBMS_OUTPUT.PUT_LINE('HI');
END IF;
 END;
 /
 
 SELECT BILL_NO,COMPANY_ID,SERVICE_ID,BILL_MONTH,BILL_YEAR,ISSUE_DATE,DUE_DATE,USED,COSTS,VAT,TOTAL,STATUS_ID,PAYMENT_DATE
 FROM BILL
 WHERE CONSUMER_ID = 150506 AND SERVICE_ID = 232450 AND PAYMENT_DATE IS NULL;
 
 SELECT TO_CHAR(TO_DATE('1','mm'),'MON')
 FROM DUAL;
 
 SELECT CONSUMER_ID,BILL_NO, DUE_DATE, FINE FROM BILL WHERE CONSUMER_ID = 150501 AND STATUS_ID = 15;
 
 
 SELECT BILL_MONTH,ISSUE_DATE,DUE_DATE,CONSUMER_ID,SERVICE_ID,COMPANY_ID
 FROM BILL WHERE BILL_NO = 3;
 
SELECT PRESENT_DATE,PREVIOUS_DATE,PRESENT_RDG,PREVIOUS_RDG,USED
FROM ELEC_USAGE
WHERE CONSUMER_ID = 150501  AND BILL_MONTH = (SELECT BILL_MONTH FROM BILL WHERE BILL_NO=3) AND BILL_YEAR=(SELECT BILL_YEAR FROM BILL WHERE BILL_NO=3) ;


SELECT PER_UNIT_COST FROM BILL_RULE WHERE COMPANY_ID = AND SERVICE_ID= AND END_DATE IS NULL;

UPDATE GETTING_SERVICE
SET STATUS_ID = 20;
COMMIT;


INSERT INTO BILL VALUES(40, 150501, 1000, 232453,1,SYSDATE,SYSDATE+7,NULL,200,23,223,15,NULL,2017,0);
--------------------------------------------------------------------------------

SELECT G.CLIENT_ID, MAX(U.PREVIOUS_RDG), MAX(U.PREVIOUS_DATE)
FROM GETTING_SERVICE G  , ELEC_USAGE U 
WHERE( G.COMPANY_ID =1000 AND G.SERVICE_ID = 232450 AND G.GS_ID = U.GS_ID) 
GROUP BY CLIENT_ID

UNION 

SELECT CLIENT_ID, INITIAL_RDG,INITIAL_DATE
FROM GETTING_SERVICE
WHERE COMPANY_ID = 1000 AND SERVICE_ID =232450 

MINUS

SELECT G.CLIENT_ID, MIN(U.PREVIOUS_RDG), MIN(U.PREVIOUS_DATE)
FROM GETTING_SERVICE G  , ELEC_USAGE U 
WHERE( G.COMPANY_ID =1000 AND G.SERVICE_ID = 232450 AND G.GS_ID = U.GS_ID) 
GROUP BY CLIENT_ID;

-----------------------------------------------
SELECT G.CLIENT_ID, MAX(U.PREVIOUS_RDG), MAX(U.PREVIOUS_DATE)
FROM GETTING_SERVICE G  JOIN ELEC_USAGE U 
ON ( G.COMPANY_ID = 1000 AND G.SERVICE_ID = 232450 AND G.GS_ID = U.GS_ID) 
GROUP BY CLIENT_ID;
----------------------------------------------

SELECT COUNT(*) FROM GETTING_SERVICE WHERE CLIENT_ID = 2074 AND SERVICE_ID=232450 AND COMPANY_ID=1000;
----------------------------------------------

SELECT TO_CHAR(PAYMENT_DATE,'DD'), SUM(TOTAL+FINE)
FROM BILL
WHERE COMPANY_ID =1002 AND BILL_MONTH = '1' AND BILL_YEAR = '2018'
GROUP BY TO_CHAR(PAYMENT_DATE,'DD');


SELECT SERVICE_NAME
FROM SERV_PROVIDER
WHERE COMPANY_ID = 1000;

SELECT S.SERVICE_NAME,BR.PER_UNIT_COST,BR.SERVICE_CHARGE,BR.FINE_RATE,BR.START_DATE,END_DATE
FROM BILL_RULE BR JOIN SERVICE S
ON(BR.SERVICE_ID=S.SERVICE_ID)
WHERE COMPANY_ID = 1000
ORDER BY BR.SERVICE_ID,START_DATE;
----------------------------------------
SELECT G.CLIENT_ID,B.BILL_NO,S.SERVICE_NAME, B.BILL_MONTH,B.BILL_YEAR,B.ISSUE_DATE,B.DUE_DATE,B.USED,B.COSTS,B.VAT,B.TOTAL,B.FINE,B.PAYMENT_DATE ,T.STATUS_NAME
FROM GETTING_SERVICE G LEFT OUTER JOIN BILL B ON (G.GS_ID = B.GS_ID)
left OUTER JOIN SERVICE S ON (B.SERVICE_ID = S.SERVICE_ID)
LEFT OUTER JOIN STATUS T ON (B.STATUS_ID = T.STATUS_ID)
WHERE G.COMPANY_ID = 1000;



JOIN STATUS T ON  (B.STATUS_ID = T.STATUS_NAME)