CREATE OR REPLACE FUNCTION BILL_CALC(B_RULE_ID IN NUMBER, USED IN NUMBER)
RETURN NUMBER IS
COSTS NUMBER;
UNIT_COST NUMBER;
S_CHRG NUMBER;
BEGIN 
SELECT PER_UNIT_COST INTO UNIT_COST FROM BILL_RULE WHERE BILL_RULE_ID = B_RULE_ID; 
SELECT SERVICE_CHARGE INTO S_CHRG FROM BILL_RULE WHERE BILL_RULE_ID = B_RULE_ID; 
COSTS := USED*UNIT_COST + S_CHRG;

RETURN COSTS;
END;
/
--DROP FUNCTION TOTAL_CALC;

DECLARE
PERS NUMBER;
BEGIN 
PERS := BILL_CALC(1,16);
DBMS_OUTPUT.PUT_LINE(PERS);
END;
/
--------------------------------
--------------------------------

CREATE OR REPLACE PROCEDURE CREATE_WATER_BILL(BILL_MONTH IN NUMBER,BILL_YEAR IN NUMBER,COM_ID IN NUMBER,VAT IN NUMBER ) IS

BILL_NO NUMBER(10);
COSTS NUMBER(10);
S_CHG NUMBER(10);
VATS NUMBER(10);
TOTAL NUMBER(10);

BEGIN

SELECT PER_UNIT_COST INTO COSTS FROM BILL_RULE WHERE COMPANY_ID = COM_ID AND SERVICE_ID=232453 AND END_DATE IS NULL;
SELECT SERVICE_CHARGE INTO S_CHG FROM BILL_RULE WHERE COMPANY_ID = COM_ID AND SERVICE_ID=232453 AND END_DATE IS NULL;
COSTS := COSTS+S_CHG;
VATS := COSTS*VAT/100;
TOTAL := COSTS + VATS;
FOR R IN (SELECT CONSUMER_ID,CLIENT_ID FROM GETTING_SERVICE WHERE SERVICE_ID = 232453 AND COMPANY_ID = COM_ID AND STATUS_ID = 20)
LOOP
     SELECT (NVL(MAX(BILL_NO),0)+1) INTO BILL_NO FROM BILL;
     
     INSERT INTO BILL VALUES(BILL_NO, R.CONSUMER_ID, COM_ID, 232453,BILL_MONTH,SYSDATE,SYSDATE+7,NULL,COSTS,VATS,TOTAL,15,NULL,BILL_YEAR,0,R.CLIENT_ID);
     
END LOOP;
COMMIT;
END;
/
--------------------------------
--------------------------------

EXEC CREATE_WATER_BILL(1,2017,1007,5);

--------------------------------
--------------------------------
CREATE OR REPLACE PROCEDURE UPDATE_BILL_FINE(CON_ID IN NUMBER) IS
COUNTER NUMBER(2);
EXTRA_DAY NUMBER(10);
FINES NUMBER(10);
f_rate NUMBER(10);
BEGIN
FOR R IN (SELECT CONSUMER_ID,COMPANY_ID,SERVICE_ID,BILL_NO, DUE_DATE, FINE FROM BILL WHERE CONSUMER_ID = CON_ID AND STATUS_ID = 15 )
LOOP

    SELECT FINE_RATE INTO f_rate FROM BILL_RULE WHERE COMPANY_ID = R.COMPANY_ID AND SERVICE_ID = R.SERVICE_ID AND END_DATE IS NULL;
    
    EXTRA_DAY:= SYSDATE - R.DUE_DATE;
    EXTRA_DAY := ROUND(EXTRA_DAY,0);
    
    DBMS_OUTPUT.PUT_LINE(R.BILL_NO||' '|| EXTRA_DAY||' '||f_rate );
    IF EXTRA_DAY > 0 THEN 
        FINES := f_rate*EXTRA_DAY;
        UPDATE BILL 
        SET FINE = FINES
        WHERE BILL_NO = R.BILL_NO;
    END IF;
END LOOP;
COMMIT;
END;
/
--------------------------------
EXEC UPDATE_BILL_FINE(150501);
ROLLBACK;
--------------------------------
CREATE OR REPLACE FUNCTION BILL_BY_COMPANY(COM_ID IN NUMBER )
RETURN NUMBER IS
SUMMATION NUMBER;
BEGIN

SELECT SUM(TOTAL) INTO SUMMATION FROM BILL WHERE COMPANY_ID = COM_ID GROUP BY COMPANY_ID; 
RETURN SUMMATION;
END;
/

CREATE OR REPLACE PROCEDURE BILL_BY_SERVICE(COM_ID IN NUMBER, MAX_SERV_INCOME OUT NUMBER, SERV_ID OUT NUMBER) IS

BEGIN
   SELECT MAX(SUM(TOTAL)) INTO MAX_SERV_INCOME FROM BILL WHERE COMPANY_ID = COM_ID GROUP BY SERVICE_ID;
   SELECT SERVICE_ID INTO SERV_ID FROM BILL WHERE COMPANY_ID = COM_ID GROUP BY SERVICE_ID HAVING SUM(TOTAL) = MAX_SERV_INCOME;

END;
/

SELECT MAX(SUM(TOTAL)),SERVICE_ID FROM BILL WHERE COMPANY_ID = 1000 GROUP BY SERVICE_ID;
SELECT SERVICE_ID  FROM BILL WHERE COMPANY_ID = 1000 GROUP BY SERVICE_ID HAVING SUM(TOTAL) = 15426;
----------------------------------------------------------------------------------------

--------------------------------------------------------------------------------


CREATE OR REPLACE PROCEDURE INSERT_CLIENT(CLIENT_ID IN NUMBER, SERV_ID IN NUMBER, COM_ID IN NUMBER,EMAIL IN VARCHAR2, PREV_RDG IN NUMBER, PREV_DATE VARCHAR2) IS

GET_SERV_ID NUMBER;
BEGIN 

SELECT (MAX(NVL(GS_ID,0))+1) INTO GET_SERV_ID FROM GETTING_SERVICE;

INSERT INTO GETTING_SERVICE VALUES(NULL, CLIENT_ID, SERV_ID, COM_ID, 20, GET_SERV_ID,EMAIL,PREV_RDG,TO_DATE(PREV_DATE,'MON DD YYYY')); 

COMMIT;
END;
/
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE  INSERT_ELEC_USAGE(CLNT_ID IN NUMBER, SERV_ID IN NUMBER, COM_ID IN NUMBER,PRS_RDG IN NUMBER, PRS_DATE VARCHAR2) IS
G_ID NUMBER;

BEGIN

 SELECT GS_ID INTO G_ID FROM GETTING_SERVICE WHERE CLIENT_ID = CLNT_ID AND SERVICE_ID = SERV_ID AND COMPANY_ID = COM_ID;

 INSERT INTO ELEC_USAGE(PRESENT_RDG, PRESENT_DATE, GS_ID) VALUES(PRS_RDG, TO_DATE(PRS_DATE,'MON DD YYYY'), G_ID);
 COMMIT;

END;
/


-----------------------------------------------------------------
-----------------------------------------------------------------

CREATE OR REPLACE FUNCTION DATE_COMPARE(FIRST_DATE IN VARCHAR2, SECOND_DATE IN VARCHAR2)

RETURN NUMBER IS 

BEGIN
   IF (TO_DATE(FIRST_DATE,'DD-MON-YY') - TO_DATE(SECOND_DATE,'MON DD YYYY')) > 0 THEN
        RETURN 1;
   ELSE 
        RETURN 0;
    END IF;
END;
/


