--------------------------------------------------------
--  File created - Monday-January-15-2018   
--------------------------------------------------------
REM INSERTING into PROJECT.BILL_RULE
SET DEFINE OFF;
Insert into PROJECT.BILL_RULE (BILL_RULE_ID,COMPANY_ID,SERVICE_ID,PER_UNIT_COST,SERVICE_CHARGE,FINE_RATE,START_DATE,END_DATE) values (1,1000,232450,3,20,10,to_date('01-JAN-18','DD-MON-RR'),to_date('07-JAN-17','DD-MON-RR'));
Insert into PROJECT.BILL_RULE (BILL_RULE_ID,COMPANY_ID,SERVICE_ID,PER_UNIT_COST,SERVICE_CHARGE,FINE_RATE,START_DATE,END_DATE) values (2,1000,232450,5,21,15,to_date('01-FEB-18','DD-MON-RR'),null);
Insert into PROJECT.BILL_RULE (BILL_RULE_ID,COMPANY_ID,SERVICE_ID,PER_UNIT_COST,SERVICE_CHARGE,FINE_RATE,START_DATE,END_DATE) values (3,1002,232450,7,30,20,null,null);
commit;