ALTER TABLE GETTING_SERVICE ADD GS_ID  NUMBER(5);
ALTER TABLE BILL ADD GS_ID NUMBER(10);

ALTER TABLE GETTING_SERVICE 
ADD CONSTRAINT GS_STATUS_ID_FK FOREIGN KEY(STATUS_ID) REFERENCES STATUS(STATUS_ID);

ALTER TABLE GETTING_SERVICE 
ADD CONSTRAINT GS_CONSUMER_ID_FK FOREIGN KEY(CONSUMER_ID) REFERENCES CONSUMER(CONSUMER_ID);

UPDATE GETTING_SERVICE
SET STATUS_ID = 20;
COMMIT;

------------------
INSERT INTO "BILL_RULE" (BILL_RULE_ID, COMPANY_ID, SERVICE_ID, PER_UNIT_COST, SERVICE_CHARGE, FINE_RATE, START_DATE) VALUES ('5', '1007', '232453', '300', '20', '12', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
ALTER TABLE BILL ADD CLIENT_ID NUMBER(10);
ALTER TABLE GETTING_SERVICE ADD GS_ID  NUMBER(10);

alter table "GETTING_SERVICE" drop constraint "GETTING_SERV_PK";
ALTER TABLE GETTING_SERVICE
ADD CONSTRAINT GETTING_SERV_PK PRIMARY KEY(GS_ID);


ALTER TABLE BILL ADD GS_ID NUMBER(10);
ALTER Table BILL
ADD CONSTRAINT BILL_GS_ID_FK FOREIGN KEY(GS_ID) REFERENCES GETTING_SERVICE(GS_ID);